### ISSUE TITLE
Clowder commands hang indefinitely after completion on GitHub Actions

### ISSUE THREAD

**Issue by reidab** [JrGoodle/clowder#463]
### Expected behavior

When running a clowder command in GitHub actions, it should do it's work and then exit. 
### Actual behavior

The command runs, does its work, and then never seems to exit.

### Steps to reproduce the behavior

This repo has a workflow that repros the problem: https://github.com/reidab/clowder-github-actions-test

Given a simple workflow file that just runs `clowder init`: https://github.com/reidab/clowder-github-actions-test/blob/master/.github/workflows/main.yml

I see results like this, where I can view the log output from the clowder command just fine, everything seems to have been completed, but GH actions doesn't recognize that the command has finished and eventually times out: https://github.com/reidab/clowder-github-actions-test/runs/648807966?check_suite_focus=true

### Environment

- `clowder` version: `3.1.0`
- OS: ubuntu-latest GitHub Action runner
- Python version: 3.8.2

**Comment by JrGoodle** [comment]
Thanks for reporting this. I haven't used GitHub Actions before, but I'll take a look tonight and see if I can get some idea of what's going on.

**Comment by reidab** [comment]
Thanks! Our best guess is that it could be something around I/O buffering and it not being a TTY environment?

**Comment by JrGoodle** [comment]
I tracked down the issue and it turns out it was due to not properly closing the multiprocess pool used for the parallel option for a few commands. Apparently that was causing an atexit handler for doing cleanup if `clowder init` fails to hang.  It only seems to happen on Python 3.8: https://bugs.python.org/issue38501

I got a quick fix onto master, but I've been making a bunch of backwards incompatible changes there for a new major version release. I'll do a patch release, but need to get my local environment set up to do a one-off deploy, so I probably won't get to that until tomorrow evening. If you don't need Python 3.8, you can specify 3.7 in the workflow description and things should work.

**Comment by JrGoodle** [comment]
Ok, pushed a new version `3.2.0` that should fix this. Fixed in commit https://github.com/JrGoodle/clowder/commit/127e9d0c411470589c4852f286775fb8b75dc48f

Thanks again for the report!
